indent-width = 4

[lint]
    extend-select = ['N', 'I']
    fixable = ['I']
    ignore = ['F403', 'F405', 'E731', 'N801', 'N802']

[format]
    quote-style = "double"
    indent-style = "space"
    preview = true
